// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  alternate_grid: dynamic(() => import("./AlternateGrid")),
  hero: dynamic(() => import("./Hero")),
  hero_2: dynamic(() => import("./Hero2")),
  hero_layout: dynamic(() => import("./HeroLayout")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  navigation_item: dynamic(() => import("./NavigationItem")),
  rich_text: dynamic(() => import("./RichText")),
};
